// Raw material for the demo data: roles, people and phrases. Everything here is invented.
// Emails use example.com, which is reserved and never delivers to anyone.
import type { EmploymentType, JobStatus, SalaryPeriod, WorkMode } from '../database/entities';

export interface MockJob {
  title: string;
  team: string;
  location: string;
  description: string;
  skills: string[];
  status: JobStatus;
  employmentType: EmploymentType;
  workMode: WorkMode;
  salaryMin: number;
  salaryMax: number;
  salaryCurrency: string;
  salaryPeriod: SalaryPeriod;
  /** How many days ago it was posted. */
  postedDaysAgo: number;
  /** Rough number of applications to generate. */
  volume: number;
  /** What a typical applicant for this role calls themselves. */
  headline: string;
  /** Skills that sit near this role but are not required by it. */
  adjacent: string[];
}

export const RECRUITERS = [
  { name: 'Priya Menon', email: 'priya.menon@hireflow.example' },
  { name: 'Daniel Okafor', email: 'daniel.okafor@hireflow.example' },
  { name: 'Sofia Alvarez', email: 'sofia.alvarez@hireflow.example' },
  { name: 'Kenji Watanabe', email: 'kenji.watanabe@hireflow.example' },
];

export const JOBS: MockJob[] = [
  {
    title: 'Software Engineer, New Grad',
    team: 'Core Platform',
    location: 'Remote, India',
    description:
      'Build internal tools and services end to end across a React front end, a NestJS API and PostgreSQL. You will own features from schema to screen, write tests alongside the code and learn how production systems behave when things go wrong. We pair new engineers with a senior mentor for the first six months.',
    skills: ['react', 'typescript', 'node.js', 'nestjs', 'postgresql', 'aws'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 1800000,
    salaryMax: 2800000,
    salaryCurrency: 'INR',
    salaryPeriod: 'year',
    postedDaysAgo: 34,
    volume: 18,
    headline: 'Software Engineer',
    adjacent: ['javascript', 'express', 'mongodb', 'docker', 'git', 'html', 'css'],
  },
  {
    title: 'Senior Backend Engineer, Payments',
    team: 'Payments',
    location: 'Bengaluru, India',
    description:
      'Own the services that move money. You will design idempotent APIs, reason about retries and partial failure, and keep a ledger correct under load. Experience with queues, PostgreSQL internals and on-call ownership matters more than any one framework.',
    skills: ['postgresql', 'typescript', 'sqs', 'kafka', 'distributed systems', 'aws'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'hybrid',
    salaryMin: 4500000,
    salaryMax: 7000000,
    salaryCurrency: 'INR',
    salaryPeriod: 'year',
    postedDaysAgo: 29,
    volume: 14,
    headline: 'Backend Engineer',
    adjacent: ['java', 'spring', 'redis', 'rabbitmq', 'mysql', 'docker', 'kubernetes'],
  },
  {
    title: 'Frontend Engineer, Design Systems',
    team: 'Product',
    location: 'Remote, Europe',
    description:
      'Build and maintain the component library used by every product team. You care about accessibility, performance budgets and APIs that are hard to misuse, and you can explain a design decision to a designer and an engineer in the same meeting.',
    skills: ['react', 'typescript', 'css', 'accessibility', 'storybook', 'testing library'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 75000,
    salaryMax: 105000,
    salaryCurrency: 'EUR',
    salaryPeriod: 'year',
    postedDaysAgo: 26,
    volume: 12,
    headline: 'Frontend Engineer',
    adjacent: ['javascript', 'vue', 'sass', 'webpack', 'figma', 'jest', 'html'],
  },
  {
    title: 'Machine Learning Engineer, Ranking',
    team: 'AI',
    location: 'Remote, US and Canada',
    description:
      'Improve how candidates and roles are matched. You will train and evaluate ranking models, build the offline evaluation that tells us whether a change helped, and ship them behind a feature flag with a rollback plan.',
    skills: ['python', 'pytorch', 'ranking', 'sql', 'evaluation', 'aws'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 150000,
    salaryMax: 210000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    postedDaysAgo: 22,
    volume: 12,
    headline: 'Machine Learning Engineer',
    adjacent: ['tensorflow', 'scikit-learn', 'pandas', 'spark', 'mlflow', 'docker', 'numpy'],
  },
  {
    title: 'Data Engineer, Pipelines',
    team: 'Data',
    location: 'London, UK',
    description:
      'Design the pipelines that turn raw events into trustworthy tables. You will work in SQL and Python, care about lineage and backfills, and write the checks that catch bad data before an analyst does.',
    skills: ['python', 'sql', 'airflow', 'spark', 'aws', 'data modelling'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'hybrid',
    salaryMin: 70000,
    salaryMax: 95000,
    salaryCurrency: 'GBP',
    salaryPeriod: 'year',
    postedDaysAgo: 19,
    volume: 10,
    headline: 'Data Engineer',
    adjacent: ['dbt', 'snowflake', 'kafka', 'pandas', 'scala', 'terraform', 'postgresql'],
  },
  {
    title: 'DevOps Engineer, Reliability',
    team: 'Infrastructure',
    location: 'Remote, Europe',
    description:
      'Keep the platform fast and boring. You will own infrastructure as code, deployment pipelines and the alarms that wake people up, and you will make the on-call experience better every quarter.',
    skills: ['aws', 'terraform', 'linux', 'ci/cd', 'observability', 'kubernetes'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 80000,
    salaryMax: 115000,
    salaryCurrency: 'EUR',
    salaryPeriod: 'year',
    postedDaysAgo: 17,
    volume: 9,
    headline: 'DevOps Engineer',
    adjacent: ['docker', 'ansible', 'prometheus', 'grafana', 'bash', 'python', 'github actions'],
  },
  {
    title: 'Product Designer',
    team: 'Design',
    location: 'Remote, worldwide',
    description:
      'Shape the recruiter and candidate experience from first sketch to shipped screen. You prototype, test with real users and work closely with engineers to get the details right.',
    skills: ['figma', 'prototyping', 'user research', 'design systems', 'interaction design'],
    status: 'open',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 95000,
    salaryMax: 135000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    postedDaysAgo: 15,
    volume: 8,
    headline: 'Product Designer',
    adjacent: ['sketch', 'illustration', 'html', 'css', 'workshops', 'accessibility'],
  },
  {
    title: 'Engineering Intern, Summer',
    team: 'Core Platform',
    location: 'Jaipur, India',
    description:
      'Twelve weeks on a real team shipping real features. You will pair with an engineer, own a small project from design to release and present it to the whole company at the end.',
    skills: ['javascript', 'react', 'git', 'sql', 'problem solving'],
    status: 'open',
    employmentType: 'internship',
    workMode: 'onsite',
    salaryMin: 40000,
    salaryMax: 60000,
    salaryCurrency: 'INR',
    salaryPeriod: 'month',
    postedDaysAgo: 12,
    volume: 15,
    headline: 'Computer Science Student',
    adjacent: ['python', 'java', 'c++', 'html', 'css', 'node.js', 'mongodb'],
  },
  {
    title: 'QA Automation Engineer',
    team: 'Quality',
    location: 'Remote, worldwide',
    description:
      'Build the end-to-end and API tests that let us ship every day. You will own the test strategy for a product area, keep the suite fast and trustworthy, and chase flaky tests until they stop being flaky.',
    skills: ['playwright', 'jest', 'api testing', 'ci/cd', 'typescript'],
    status: 'open',
    employmentType: 'contract',
    workMode: 'remote',
    salaryMin: 45,
    salaryMax: 70,
    salaryCurrency: 'USD',
    salaryPeriod: 'hour',
    postedDaysAgo: 9,
    volume: 8,
    headline: 'QA Engineer',
    adjacent: ['selenium', 'cypress', 'postman', 'javascript', 'python', 'jenkins'],
  },
  {
    title: 'AI Trainer, Software Engineering',
    team: 'AI',
    location: 'Remote, worldwide',
    description:
      'Review and improve how language models write code. You will write careful rubrics, grade model answers against them, and explain your reasoning so the next reviewer can agree or disagree with it.',
    skills: ['code review', 'python', 'javascript', 'rubric design', 'technical writing'],
    status: 'open',
    employmentType: 'contract',
    workMode: 'remote',
    salaryMin: 40,
    salaryMax: 90,
    salaryCurrency: 'USD',
    salaryPeriod: 'hour',
    postedDaysAgo: 6,
    volume: 10,
    headline: 'Software Engineer',
    adjacent: ['typescript', 'java', 'go', 'testing', 'git', 'documentation'],
  },
  {
    title: 'Security Engineer',
    team: 'Infrastructure',
    location: 'Remote, Europe',
    description:
      'Find the problems before someone else does. Threat modelling, code review for security, and building the guardrails that make the secure path the easy one. This role is paused while we rework the team plan.',
    skills: ['threat modelling', 'aws', 'owasp', 'python', 'penetration testing'],
    status: 'paused',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 95000,
    salaryMax: 135000,
    salaryCurrency: 'EUR',
    salaryPeriod: 'year',
    postedDaysAgo: 38,
    volume: 6,
    headline: 'Security Engineer',
    adjacent: ['linux', 'networking', 'burp suite', 'go', 'docker', 'iam'],
  },
  {
    title: 'Engineering Manager, Platform',
    team: 'Core Platform',
    location: 'Bengaluru, India',
    description:
      'Lead a team of six engineers building the platform other teams rely on. This role has been filled, and the posting is closed.',
    skills: ['people management', 'system design', 'typescript', 'hiring', 'roadmapping'],
    status: 'closed',
    employmentType: 'full_time',
    workMode: 'hybrid',
    salaryMin: 6500000,
    salaryMax: 9500000,
    salaryCurrency: 'INR',
    salaryPeriod: 'year',
    postedDaysAgo: 40,
    volume: 7,
    headline: 'Engineering Lead',
    adjacent: ['java', 'aws', 'agile', 'mentoring', 'budgeting', 'python'],
  },
  {
    title: 'Solutions Architect',
    team: 'Customer Engineering',
    location: 'Remote, US',
    description: 'Help customers design their integration with HireFlow. Draft while the team finalises the brief.',
    skills: ['aws', 'api design', 'solution design', 'sql', 'communication'],
    status: 'draft',
    employmentType: 'full_time',
    workMode: 'remote',
    salaryMin: 130000,
    salaryMax: 175000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    postedDaysAgo: 2,
    volume: 0,
    headline: 'Solutions Engineer',
    adjacent: ['python', 'javascript', 'presales', 'rest', 'docker'],
  },
];

export const FIRST_NAMES = [
  'Aarav',
  'Ananya',
  'Rohan',
  'Isha',
  'Vikram',
  'Meera',
  'Arjun',
  'Kavya',
  'Siddharth',
  'Neha',
  'Liam',
  'Emma',
  'Noah',
  'Olivia',
  'Ethan',
  'Ava',
  'Lucas',
  'Mia',
  'Mateo',
  'Sofia',
  'Wei',
  'Mei',
  'Hiro',
  'Yuki',
  'Min-jun',
  'Seo-yeon',
  'Linh',
  'Anh',
  'Budi',
  'Siti',
  'Chidi',
  'Amara',
  'Kwame',
  'Zainab',
  'Tendai',
  'Naledi',
  'Omar',
  'Layla',
  'Yusuf',
  'Fatima',
  'Lars',
  'Ingrid',
  'Pavel',
  'Katarina',
  'Giulia',
  'Marco',
  'Elena',
  'Dmitri',
  'Anja',
  'Tomas',
  'Zoe',
  'Jack',
  'Grace',
  'Henry',
  'Chloe',
  'Oscar',
  'Ruby',
  'Felix',
  'Nora',
  'Theo',
];

export const LAST_NAMES = [
  'Sharma',
  'Iyer',
  'Reddy',
  'Gupta',
  'Nair',
  'Kapoor',
  'Joshi',
  'Bose',
  'Malhotra',
  'Rao',
  'Smith',
  'Johnson',
  'Brown',
  'Taylor',
  'Wilson',
  'Clarke',
  'Hughes',
  'Patel',
  'Morgan',
  'Hayes',
  'Zhang',
  'Chen',
  'Tanaka',
  'Suzuki',
  'Kim',
  'Park',
  'Nguyen',
  'Tran',
  'Santoso',
  'Wijaya',
  'Okafor',
  'Adeyemi',
  'Mensah',
  'Dlamini',
  'Nkosi',
  'Hassan',
  'Rahman',
  'Khalil',
  'Haddad',
  'Aziz',
  'Larsen',
  'Novak',
  'Rossi',
  'Bianchi',
  'Ivanov',
  'Kowalski',
  'Muller',
  'Schmidt',
  'Silva',
  'Costa',
];

export const CITIES = [
  'Bengaluru',
  'Pune',
  'Hyderabad',
  'Jaipur',
  'Delhi',
  'Mumbai',
  'London',
  'Berlin',
  'Lisbon',
  'Warsaw',
  'Toronto',
  'Austin',
  'Seattle',
  'Singapore',
  'Lagos',
  'Nairobi',
  'Sao Paulo',
  'Dubai',
  'Sydney',
  'Dublin',
];

export const COMPANIES = [
  'Brightwave Labs',
  'Northfield Systems',
  'Kestrel Software',
  'Lumen Data',
  'Harbor Analytics',
  'Pinecone Digital',
  'Orbit Logistics',
  'Maple Fintech',
  'Cobalt Cloud',
  'Saffron Health',
  'Tidal Commerce',
  'Granite Networks',
  'Juniper Media',
  'Atlas Mobility',
  'Copperline Retail',
];

export const COLLEGES = [
  'Northfield University',
  'Lakeside Institute of Technology',
  'Eastbridge College of Engineering',
  'Redwood State University',
  'Highland Technical University',
  'Riverstone Institute of Science',
];

/** Fields for resumes that do not match a technical role at all. */
export const UNRELATED = [
  {
    headline: 'Sales Operations Associate',
    skills: ['salesforce', 'forecasting', 'excel', 'customer success', 'negotiation'],
  },
  {
    headline: 'Mechanical Design Engineer',
    skills: ['solidworks', 'cad', 'manufacturing', 'tolerancing', 'prototyping hardware'],
  },
  {
    headline: 'Content Marketing Manager',
    skills: ['seo', 'copywriting', 'campaigns', 'analytics dashboards', 'social media'],
  },
  {
    headline: 'Retail Store Supervisor',
    skills: ['inventory', 'scheduling', 'customer service', 'cash handling', 'merchandising'],
  },
];

export const NOTES = {
  screening: [
    'Resume looks relevant, moving to a closer read',
    'Strong signal on the required stack, starting screening',
    'Shortlisted from the weekly review',
  ],
  interview: [
    'Phone screen went well: clear thinking about trade-offs',
    'Good project depth. Scheduling the technical round',
    'Invited after the hiring manager review',
  ],
  offer: ['Panel was unanimous. Preparing the offer', 'Strong across all rounds, offer approved by the hiring manager'],
  hired: ['Offer accepted, start date confirmed', 'Signed. Onboarding scheduled'],
  rejected: [
    'Not enough depth on the core requirements for this role',
    'Strong profile, but we are going with a candidate who is closer to the stack',
    'Role requirements not met after the technical screen',
  ],
  withdrawn: [
    'Candidate accepted another offer',
    'Candidate withdrew: relocation was not possible',
    'Candidate no longer available',
  ],
};
